"""`carto capabilities` — the machine-readable command catalogue.

This is the contract's recovery path. Skills are authoritative for *how* to work
(they teach workflows), but a skill can be skipped, stale, or absent on a host
we did not anticipate. When that happens the agent still needs to discover the
surface, and `carto capabilities` is how: a bounded JSON catalogue of every
command, its arguments, and a runnable example.

It also does load-bearing work for token economy. Because the reference detail
lives here, skill bodies do not have to carry it — they can describe four or
five commands for a workflow and point at this for the long tail.

**The catalogue is generated by introspecting the live argparse parser**, never
hand-maintained. A hand-written catalogue drifts from the CLI the moment someone
adds a flag, and a catalogue that lies is worse than none — the agent would
confidently invoke commands that do not exist. This is the same class of bug as
the `query` choices list that hid eight patterns for who knows how long.
"""

from __future__ import annotations

import argparse
from typing import Any, Optional

#: Commands that exist for humans or installation, not for agents. Listing them
#: spends an agent's context on things it should never call.
_NOT_AGENT_FACING = frozenset({
    "install", "init", "uninstall", "serve", "mcp", "daemon", "watch", "eval",
    "register", "unregister", "capabilities",
})

#: A runnable example per command. Examples do more than illustrate — they are
#: the fastest way for a model to infer argument order and shape.
_EXAMPLES = {
    "status": "carto status --format json",
    "query": "carto query callers_of parse_args --limit 20",
    "impact": "carto impact --files src/auth.py --format json",
    "search": "carto search 'token budget' --limit 10",
    "flows": "carto flows --sort criticality --limit 10",
    "flow": "carto flow --name checkout",
    "communities": "carto communities --min-size 5",
    "community": "carto community --name auth",
    "architecture": "carto architecture --detail-level standard",
    "large-functions": "carto large-functions --min-lines 80",
    "refactor": "carto refactor rename --old-name foo --new-name bar",
    "build": "carto build",
    "update": "carto update",
    "detect-changes": "carto detect-changes --base HEAD~1",
    "dead-code": "carto dead-code --format json",
    "enrich": "carto enrich",
    "repos": "carto repos",
    "postprocess": "carto postprocess",
    "embed": "carto embed",
    "wiki": "carto wiki",
    "visualize": "carto visualize",
    "forget": "carto forget src/old.py",
}

#: One line on when an agent should reach for each command. This is the part a
#: model actually uses to choose, so it is phrased as a decision, not a summary.
_WHEN = {
    "status": "Check whether a graph exists and is current, before relying on any other command.",
    "query": "Answer a structural question about one symbol or file — who calls it, what it imports, what tests cover it.",
    "impact": "Find the blast radius of a change before making or reviewing it.",
    "search": "Find nodes by name or meaning when you do not know the exact symbol.",
    "flows": "See the execution flows the graph has detected.",
    "flow": "Read one execution flow end to end.",
    "communities": "See how the codebase clusters into related groups.",
    "community": "Read one cluster in detail.",
    "architecture": "Get a high-level map before exploring an unfamiliar codebase.",
    "large-functions": "Find oversized functions worth refactoring or reviewing closely.",
    "refactor": "Preview a rename or signature change across the graph. Previews only.",
    "build": "Create the graph. Required once before anything else works.",
    "update": "Refresh the graph after edits. Cheaper than a rebuild.",
    "detect-changes": "See what changed against a base ref, with graph context.",
    "dead-code": "Find nodes nothing references — candidates for deletion.",
    "repos": "List registered repositories for cross-repo work.",
}


def _flag_entry(action: argparse.Action) -> Optional[dict[str, Any]]:
    """Describe one argparse action, or None if it should not be listed."""
    if action.dest in ("help", "==SUPPRESS=="):
        return None
    entry: dict[str, Any] = {"name": action.dest}
    if action.option_strings:
        entry["flag"] = max(action.option_strings, key=len)
    else:
        entry["positional"] = True
        entry["required"] = True
    if action.choices:
        entry["choices"] = list(action.choices)
    if action.default not in (None, False) and not action.option_strings:
        entry["default"] = action.default
    elif action.default not in (None, False):
        entry["default"] = action.default
    if action.help and action.help != argparse.SUPPRESS:
        entry["help"] = action.help
    return entry


def _command_entry(
    name: str,
    parser: argparse.ArgumentParser,
    *,
    full: bool,
    fallback_help: str = "",
) -> dict[str, Any]:
    # `when` prefers the curated decision-phrased line, then the `help=` given
    # to add_parser (which argparse keeps on the parent action, not here), then
    # the parser's own description.
    when = (
        _WHEN.get(name)
        or fallback_help
        or (parser.description or "")
    ).strip()
    entry: dict[str, Any] = {
        "name": name,
        "when": when,
        "example": _EXAMPLES.get(name, f"carto {name}"),
    }
    if not full:
        return entry
    args: list[dict[str, Any]] = []
    flags: list[dict[str, Any]] = []
    for action in parser._actions:  # noqa: SLF001 — argparse exposes no public API
        described = _flag_entry(action)
        if described is None:
            continue
        (args if described.get("positional") else flags).append(described)
    entry["arguments"] = args
    entry["flags"] = flags
    return entry


def build_catalogue(
    parser: argparse.ArgumentParser,
    *,
    command: Optional[str] = None,
    version: str = "unknown",
) -> dict[str, Any]:
    """Introspect the live parser into a catalogue.

    Without ``command`` this is the compact listing: every agent-facing command
    with when-to-use and an example, and nothing else. That keeps the default
    response small enough for an agent to read speculatively.

    With ``command`` it returns full argument and flag detail for that one
    command — the drill-down an agent does once it knows what it wants.
    """
    subparsers = next(
        (a for a in parser._actions if isinstance(a, argparse._SubParsersAction)),  # noqa: SLF001
        None,
    )
    catalogue: dict[str, Any] = {
        "contract": "capability-v1",
        "envelope_schema": 1,
        "tool": "cartograph",
        "binary": "carto",
        "version": version,
        "conventions": {
            "format": "Every command accepts --format json|text. Agents should always pass json.",
            "budget": "--max-tokens bounds the response. Truncation is semantic, never a byte cut.",
            "exit_codes": {
                "0": "success — an empty result is success, not an error",
                "1": "usage error — the call was malformed",
                "2": "precondition unmet — read error.remediation and act on it, then retry",
                "3": "internal error",
            },
            "paging": "List results carry a page block. At most one collection per response pages.",
        },
    }
    if subparsers is None:
        catalogue["commands"] = []
        return catalogue

    if command:
        sub = subparsers.choices.get(command)
        if sub is None:
            known = sorted(c for c in subparsers.choices if c not in _NOT_AGENT_FACING)
            raise KeyError(
                f"unknown command {command!r}; agent-facing commands are: {', '.join(known)}"
            )
        catalogue["commands"] = [_command_entry(command, sub, full=True)]
        return catalogue

    # argparse stores the `help=` text from add_parser on the parent action,
    # not on the subparser, so it has to be recovered separately.
    help_for = {
        a.dest: (a.help or "")
        for a in getattr(subparsers, "_choices_actions", [])
    }

    seen: set[int] = set()
    commands = []
    for name, sub in subparsers.choices.items():
        if name in _NOT_AGENT_FACING:
            continue
        # argparse registers aliases as separate keys pointing at one parser;
        # listing the same command twice would just cost the agent context.
        if id(sub) in seen:
            continue
        seen.add(id(sub))
        commands.append(
            _command_entry(name, sub, full=False, fallback_help=help_for.get(name, ""))
        )
    catalogue["commands"] = sorted(commands, key=lambda c: c["name"])
    catalogue["detail"] = "For full flags on one command: carto capabilities --command <name>"
    return catalogue
